# Setup
title:        "Whiteglad" 
tagline:      "Every butterfly is evolved from a flower"
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       "Vincent Liu"
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
